version : '3'
services :
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpressdb.c4gucir4zekt.eu-west-3.rds.amazonaws.com
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpressnp
      WORDPRESS_DB_NAME: wordpressdb

volumes:
  db_data: {}
